[versions]
kotlin = "2.0.21"
kotlinx-coroutines = "1.7.3"
dokka = "1.8.20"
run-task = "3.0.2"

architectury = "1.13-SNAPSHOT"
shadow = "8.1.1"
asm = "9.6"

annotations = "23.0.0"
guava = "33.3.1-jre"
slf4j = "1.7.30"
semver4j = "6.0.0"

spigot = "1.16.5-R0.1-SNAPSHOT"
folia = "1.20.1-R0.1-SNAPSHOT"
velocity = "3.1.1"
bungee = "1.21-R0.4-SNAPSHOT"

minestom = "2025.10.05-1.21.8"

adventure = "4.21.0"
adventure-platform = "4.4.0"
fabric-permissions = "0.3.1"

reflection-remapper = "0.1.2"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

annotations  = { module = "org.jetbrains:annotations", version.ref = "annotations" }
guava        = { module = "com.google.guava:guava", version.ref = "guava" }
slf4j        = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
semver4j     = { module = "org.semver4j:semver4j", version.ref = "semver4j" }

spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
folia = { module = "dev.folia:folia-api", version.ref = "folia" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungee-api = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }
bungee-proxy = { module = "net.md-5:bungeecord-proxy", version.ref = "bungee" }

minestom = { module = "net.minestom:minestom", version.ref = "minestom" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-gson = { module = "net.kyori:adventure-text-serializer-gson", version.ref = "adventure" }
adventure-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platform" }
adventure-bungee = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platform" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }

reflectionremapper = { module = "xyz.jpenilla:reflection-remapper", version.ref = "reflection-remapper" }

shadow = { module = "com.github.johnrengelman:shadow", version.ref = "shadow" }
asm = { module = "org.ow2.asm:asm-commons", version.ref = "asm" }

[plugins]
architectury = { id = "dev.architectury.loom", version.ref = "architectury" }
dokka  = { id = "org.jetbrains.dokka", version.ref = "dokka" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "run-task"}
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "run-task"}
run-waterfall = { id = "xyz.jpenilla.run-waterfall", version.ref = "run-task"}
