[versions]
kotlin = "1.8.22"
kotlinx-coroutines = "1.7.3"
dokka = "1.8.20"

shadow = "7.1.0"

guava = "31.1-jre"
slf4j = "1.7.30"

spigot = "1.16.5-R0.1-SNAPSHOT"
folia = "1.20.1-R0.1-SNAPSHOT"
velocity = "3.1.1"
bungee = "1.19-R0.1-SNAPSHOT"

minestom = "7320437640"
minestom-extensions = "1.2.0"

adventure = "4.14.0"
fabric-permissions = "0.2-SNAPSHOT"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "kotlinx-coroutines" }

guava        = { module = "com.google.guava:guava", version.ref = "guava" }
slf4j        = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }

spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
folia = { module = "dev.folia:folia-api", version.ref = "folia" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungee-api = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }
bungee-proxy = { module = "net.md-5:bungeecord-proxy", version.ref = "bungee" }

minestom = { module = "net.minestom:minestom-snapshots", version.ref = "minestom" }
minestom-extension = { module = "dev.hollowcube:minestom-ce-extensions", version.ref = "minestom-extensions" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
dokka  = { id = "org.jetbrains.dokka", version.ref = "dokka" }
